# MyceliumFractalNet v4.1 Kubernetes Deployment
# Supports scaling to 1M clients via horizontal pod autoscaling

apiVersion: v1
kind: Namespace
metadata:
  name: mycelium-fractal-net
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycelium-fractal-net
  namespace: mycelium-fractal-net
  labels:
    app: mycelium-fractal-net
    version: v4.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mycelium-fractal-net
  template:
    metadata:
      labels:
        app: mycelium-fractal-net
        version: v4.1
    spec:
      containers:
        - name: mycelium-fractal-net
          image: mycelium-fractal-net:v4.1
          imagePullPolicy: IfNotPresent
          command: ["uvicorn"]
          args: ["api:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8000
              name: http
          resources:
            # Note: Large gap between requests and limits is intentional
            # /validate and /simulate endpoints are expensive but bursty
            # Normal operation uses ~512Mi, but validation can spike to 2Gi
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MFN_SEED
              value: "42"
            - name: MFN_ENV
              value: "prod"
            - name: MFN_API_KEY_REQUIRED
              value: "true"
            - name: MFN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mfn-secrets
                  key: api-key
            - name: MFN_RATE_LIMIT_ENABLED
              value: "true"
            - name: MFN_RATE_LIMIT_REQUESTS
              value: "100"
            - name: MFN_LOG_FORMAT
              value: "json"
            - name: MFN_LOG_LEVEL
              value: "INFO"
            - name: MFN_METRICS_ENABLED
              value: "true"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mycelium-fractal-net
  namespace: mycelium-fractal-net
spec:
  selector:
    app: mycelium-fractal-net
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mycelium-fractal-net-hpa
  namespace: mycelium-fractal-net
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mycelium-fractal-net
  minReplicas: 3
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# ConfigMap for model configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycelium-config
  namespace: mycelium-fractal-net
data:
  config.json: |
    {
      "seed": 42,
      "epochs": 1,
      "batch_size": 4,
      "grid_size": 64,
      "steps": 64,
      "turing_enabled": true,
      "quantum_jitter": false,
      "use_sparse_attention": true,
      "use_stdp": true
    }
---
# Secret for API keys and sensitive configuration
# REQUIRED: Create this secret before deploying:
#   kubectl create secret generic mfn-secrets \
#     --from-literal=api-key=$(openssl rand -base64 32) \
#     -n mycelium-fractal-net
#
# This manifest is provided as a template only.
# DO NOT apply this file directly - it will fail due to missing required secret data.
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mfn-secrets
#   namespace: mycelium-fractal-net
# type: Opaque
# data:
#   api-key: <REQUIRED - create via kubectl command above>
---
# Ingress for external HTTP(S) access
# Note: Requires an ingress controller (nginx, traefik, etc.)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mycelium-ingress
  namespace: mycelium-fractal-net
  annotations:
    # Nginx ingress annotations
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "100"
    # CORS - REQUIRED: Set MFN_CORS_ORIGINS environment variable in deployment
    # For production, explicitly configure allowed origins via environment variable
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "https://your-domain.com"
    # Cert-manager for automatic TLS
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mfn.example.com
      secretName: mfn-tls-secret
  rules:
    - host: mfn.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mycelium-fractal-net
                port:
                  number: 80
---
# NetworkPolicy to restrict pod-to-pod communication
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mfn-network-policy
  namespace: mycelium-fractal-net
spec:
  podSelector:
    matchLabels:
      app: mycelium-fractal-net
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
    # Allow traffic from monitoring namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: 8000
  egress:
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow external HTTPS (for API calls if needed)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
---
# PodDisruptionBudget to ensure availability during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mfn-pdb
  namespace: mycelium-fractal-net
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: mycelium-fractal-net
---
# ServiceMonitor for Prometheus metrics scraping
# Note: Requires prometheus-operator
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mfn-metrics
  namespace: mycelium-fractal-net
  labels:
    app: mycelium-fractal-net
spec:
  selector:
    matchLabels:
      app: mycelium-fractal-net
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
