# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import mycelium_pb2 as protos_dot_mycelium__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/mycelium_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MyceliumServiceStub(object):
    """MyceliumFractalNet gRPC Service
    Provides high-performance RPC interface for fractal neural network operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Validate = channel.unary_unary(
                '/mycelium.MyceliumService/Validate',
                request_serializer=protos_dot_mycelium__pb2.ValidateRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.Simulate = channel.unary_unary(
                '/mycelium.MyceliumService/Simulate',
                request_serializer=protos_dot_mycelium__pb2.SimulateRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.SimulateResponse.FromString,
                _registered_method=True)
        self.SimulateStream = channel.unary_stream(
                '/mycelium.MyceliumService/SimulateStream',
                request_serializer=protos_dot_mycelium__pb2.SimulateRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.SimulationUpdate.FromString,
                _registered_method=True)
        self.ComputeNernst = channel.unary_unary(
                '/mycelium.MyceliumService/ComputeNernst',
                request_serializer=protos_dot_mycelium__pb2.NernstRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.NernstResponse.FromString,
                _registered_method=True)
        self.AggregateFederated = channel.unary_unary(
                '/mycelium.MyceliumService/AggregateFederated',
                request_serializer=protos_dot_mycelium__pb2.FederatedAggregateRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.FederatedAggregateResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/mycelium.MyceliumService/HealthCheck',
                request_serializer=protos_dot_mycelium__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=protos_dot_mycelium__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MyceliumServiceServicer(object):
    """MyceliumFractalNet gRPC Service
    Provides high-performance RPC interface for fractal neural network operations
    """

    def Validate(self, request, context):
        """Run validation cycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simulate(self, request, context):
        """Simulate mycelium field
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimulateStream(self, request, context):
        """Stream simulation updates in real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeNernst(self, request, context):
        """Compute Nernst potential
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateFederated(self, request, context):
        """Aggregate federated learning gradients
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyceliumServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=protos_dot_mycelium__pb2.ValidateRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.ValidateResponse.SerializeToString,
            ),
            'Simulate': grpc.unary_unary_rpc_method_handler(
                    servicer.Simulate,
                    request_deserializer=protos_dot_mycelium__pb2.SimulateRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.SimulateResponse.SerializeToString,
            ),
            'SimulateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SimulateStream,
                    request_deserializer=protos_dot_mycelium__pb2.SimulateRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.SimulationUpdate.SerializeToString,
            ),
            'ComputeNernst': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeNernst,
                    request_deserializer=protos_dot_mycelium__pb2.NernstRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.NernstResponse.SerializeToString,
            ),
            'AggregateFederated': grpc.unary_unary_rpc_method_handler(
                    servicer.AggregateFederated,
                    request_deserializer=protos_dot_mycelium__pb2.FederatedAggregateRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.FederatedAggregateResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=protos_dot_mycelium__pb2.HealthCheckRequest.FromString,
                    response_serializer=protos_dot_mycelium__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mycelium.MyceliumService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mycelium.MyceliumService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MyceliumService(object):
    """MyceliumFractalNet gRPC Service
    Provides high-performance RPC interface for fractal neural network operations
    """

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycelium.MyceliumService/Validate',
            protos_dot_mycelium__pb2.ValidateRequest.SerializeToString,
            protos_dot_mycelium__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Simulate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycelium.MyceliumService/Simulate',
            protos_dot_mycelium__pb2.SimulateRequest.SerializeToString,
            protos_dot_mycelium__pb2.SimulateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SimulateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mycelium.MyceliumService/SimulateStream',
            protos_dot_mycelium__pb2.SimulateRequest.SerializeToString,
            protos_dot_mycelium__pb2.SimulationUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeNernst(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycelium.MyceliumService/ComputeNernst',
            protos_dot_mycelium__pb2.NernstRequest.SerializeToString,
            protos_dot_mycelium__pb2.NernstResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateFederated(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycelium.MyceliumService/AggregateFederated',
            protos_dot_mycelium__pb2.FederatedAggregateRequest.SerializeToString,
            protos_dot_mycelium__pb2.FederatedAggregateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mycelium.MyceliumService/HealthCheck',
            protos_dot_mycelium__pb2.HealthCheckRequest.SerializeToString,
            protos_dot_mycelium__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
