# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mfn_pb2 as grpc_dot_proto_dot_mfn__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc/proto/mfn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MFNFeaturesServiceStub(object):
    """=============================================================================
    Feature Extraction Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExtractFeatures = channel.unary_unary(
                '/mfn.MFNFeaturesService/ExtractFeatures',
                request_serializer=grpc_dot_proto_dot_mfn__pb2.FeatureRequest.SerializeToString,
                response_deserializer=grpc_dot_proto_dot_mfn__pb2.FeatureResponse.FromString,
                _registered_method=True)
        self.StreamFeatures = channel.unary_stream(
                '/mfn.MFNFeaturesService/StreamFeatures',
                request_serializer=grpc_dot_proto_dot_mfn__pb2.FeatureStreamRequest.SerializeToString,
                response_deserializer=grpc_dot_proto_dot_mfn__pb2.FeatureFrame.FromString,
                _registered_method=True)


class MFNFeaturesServiceServicer(object):
    """=============================================================================
    Feature Extraction Service
    =============================================================================

    """

    def ExtractFeatures(self, request, context):
        """Extract features from a simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFeatures(self, request, context):
        """Stream features in real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MFNFeaturesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExtractFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFeatures,
                    request_deserializer=grpc_dot_proto_dot_mfn__pb2.FeatureRequest.FromString,
                    response_serializer=grpc_dot_proto_dot_mfn__pb2.FeatureResponse.SerializeToString,
            ),
            'StreamFeatures': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFeatures,
                    request_deserializer=grpc_dot_proto_dot_mfn__pb2.FeatureStreamRequest.FromString,
                    response_serializer=grpc_dot_proto_dot_mfn__pb2.FeatureFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mfn.MFNFeaturesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mfn.MFNFeaturesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MFNFeaturesService(object):
    """=============================================================================
    Feature Extraction Service
    =============================================================================

    """

    @staticmethod
    def ExtractFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mfn.MFNFeaturesService/ExtractFeatures',
            grpc_dot_proto_dot_mfn__pb2.FeatureRequest.SerializeToString,
            grpc_dot_proto_dot_mfn__pb2.FeatureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mfn.MFNFeaturesService/StreamFeatures',
            grpc_dot_proto_dot_mfn__pb2.FeatureStreamRequest.SerializeToString,
            grpc_dot_proto_dot_mfn__pb2.FeatureFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MFNSimulationServiceStub(object):
    """=============================================================================
    Simulation Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunSimulation = channel.unary_unary(
                '/mfn.MFNSimulationService/RunSimulation',
                request_serializer=grpc_dot_proto_dot_mfn__pb2.SimulationRequest.SerializeToString,
                response_deserializer=grpc_dot_proto_dot_mfn__pb2.SimulationResult.FromString,
                _registered_method=True)
        self.StreamSimulation = channel.unary_stream(
                '/mfn.MFNSimulationService/StreamSimulation',
                request_serializer=grpc_dot_proto_dot_mfn__pb2.SimulationStreamRequest.SerializeToString,
                response_deserializer=grpc_dot_proto_dot_mfn__pb2.SimulationFrame.FromString,
                _registered_method=True)


class MFNSimulationServiceServicer(object):
    """=============================================================================
    Simulation Service
    =============================================================================

    """

    def RunSimulation(self, request, context):
        """Run a single simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSimulation(self, request, context):
        """Stream simulation state in real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MFNSimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.RunSimulation,
                    request_deserializer=grpc_dot_proto_dot_mfn__pb2.SimulationRequest.FromString,
                    response_serializer=grpc_dot_proto_dot_mfn__pb2.SimulationResult.SerializeToString,
            ),
            'StreamSimulation': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSimulation,
                    request_deserializer=grpc_dot_proto_dot_mfn__pb2.SimulationStreamRequest.FromString,
                    response_serializer=grpc_dot_proto_dot_mfn__pb2.SimulationFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mfn.MFNSimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mfn.MFNSimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MFNSimulationService(object):
    """=============================================================================
    Simulation Service
    =============================================================================

    """

    @staticmethod
    def RunSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mfn.MFNSimulationService/RunSimulation',
            grpc_dot_proto_dot_mfn__pb2.SimulationRequest.SerializeToString,
            grpc_dot_proto_dot_mfn__pb2.SimulationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mfn.MFNSimulationService/StreamSimulation',
            grpc_dot_proto_dot_mfn__pb2.SimulationStreamRequest.SerializeToString,
            grpc_dot_proto_dot_mfn__pb2.SimulationFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MFNValidationServiceStub(object):
    """=============================================================================
    Validation Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidatePattern = channel.unary_unary(
                '/mfn.MFNValidationService/ValidatePattern',
                request_serializer=grpc_dot_proto_dot_mfn__pb2.ValidationRequest.SerializeToString,
                response_deserializer=grpc_dot_proto_dot_mfn__pb2.ValidationResult.FromString,
                _registered_method=True)


class MFNValidationServiceServicer(object):
    """=============================================================================
    Validation Service
    =============================================================================

    """

    def ValidatePattern(self, request, context):
        """Validate a pattern/configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MFNValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidatePattern': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePattern,
                    request_deserializer=grpc_dot_proto_dot_mfn__pb2.ValidationRequest.FromString,
                    response_serializer=grpc_dot_proto_dot_mfn__pb2.ValidationResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mfn.MFNValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mfn.MFNValidationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MFNValidationService(object):
    """=============================================================================
    Validation Service
    =============================================================================

    """

    @staticmethod
    def ValidatePattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mfn.MFNValidationService/ValidatePattern',
            grpc_dot_proto_dot_mfn__pb2.ValidationRequest.SerializeToString,
            grpc_dot_proto_dot_mfn__pb2.ValidationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
